### ISSUE TITLE
 Debian OS bug fix in certificate path

### ISSUE THREAD

**Issue by PriyankaVerma98** [oracle/fluent-plugin-oci-logging#2]
A bug in the repository which causes a runtime error on initialization under Debian. The default directory for CA certificates is not applicable for Debian which causes failure upon configuration.

Internal Links:
https://jira.oci.oraclecorp.com/browse/UA-2388 
https://jira-sd.mc1.oracleiaas.com/browse/UAOPS-2655

**Comment by Spoorthy-oci** [comment]
Fix has been merged
